version: "3.9"

services:
  fastapi:
    build:
      context: ..
      dockerfile: ./docker/fastapi/Dockerfile
    container_name: fastapi-app
    restart: always
    working_dir: /app
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/src:cached
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8080




