version: "3.9"

services:
  fastapi:
    build:
      context: ..
      dockerfile: ./docker/fastapi/Dockerfile
    container_name: fastapi-app
    restart: always
    working_dir: /src
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src:cached
    command: uvicorn src.main:app --reload 




